---
title: Handboek Communicatie Kunstuitleen 2.0
timezone: Europe/Amsterdam
collections:
  bronnen:
    title: Bronnen
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Overzicht van gebruikte bronnen voor dit handboek
      badge: "/uploads/badge--bron.svg"
      in_nav: true
    position: 50
  credits:
    title: Credits
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Dankwoord aan alle betrokkenen
      badge: "/uploads/badge--credits.svg"
      in_nav: true
    position: 70
  handboek:
    title: Handboek Kunst2.0
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Over klanten en hoe continue beter met hen te communiceren
      badge: "/uploads/badge--handbook.svg"
      in_nav: true
    position: 30
  leeswijzer:
    title: Leeswijzer
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Leer meer over dit handboek zelf
      badge: "/uploads/badge--lees.svg"
      in_nav: true
    position: 10
  v1:
    title: Legacy Sites
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Moving from v1 to v2
      badge: "/uploads/badge--v1.svg"
      in_nav: false
    position: 70
  weten:
    title: Meer weten
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Bijlagen, methodische verantwoording, achtergrondinformatie
      badge: "/uploads/badge--more.svg"
      in_nav: true
    position: 40
  posts:
    title: Posts
    output: true
  style:
    title: Stijlgids
    output: true
    permalink: "/:collection/:path/"
    meta:
      description: Visuele communicatie
      badge: "/uploads/badge--style.svg"
      in_nav: true
    position: 10  
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: leeswijzer
  values:
    layout: page
    color: blue
- scope:
    path: ''
    type: handboek
  values:
    layout: page
    color: blue
- scope:
    path: ''
    type: weten
  values:
    layout: page
    color: blue
- scope:
    path: ''
    type: bronnen
  values:
    layout: page
    color: blue
- scope:
    path: ''
    type: credits
  values:
    layout: page
    color: blue
- scope:
    path: ''
    type: v1
  values:
    layout: page
    color: blue
- scope:
    path: ''
    type: style
  values:
    layout: page
    color: blue
url: https://kunstuitleenzwolle.github.io/hndbk/
permalink: pretty
github_url: https://github.com/kunstuitleenzwolle/hndbk
sass:
  style: compressed
gems:
- jekyll-sitemap
- jekyll-seo-tag
logo: "/assets/images/Logo_KUZ.svg"
